name: Check

on:
  push:
    branches: []
    paths:
      - 'src/*'
      - '*.json'
      - '.github/workflows/check.yml'
  pull_request:
    branches: []
    paths:
      - 'src/*'
      - '*.json'
      - '.github/workflows/check.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Restore node modules cache
        uses: actions/cache@v4
        with:
          path: ./node_modules/
          key: npm-${{ hashFiles('package.json') }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Check
        run: npm run test:coverage
